{
 "title": "windows_exporter for Prometheus Dashboard EN v20231004 new",
 "description": "【English version】Update 2023.10.04,  Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics",
 "tags": [
  "Prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(windows_cs_hostname, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\"}, hostname)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",hostname=~\"$hostname\"}, instance)"
    }
   },
   {
    "name": "show_hostname",
    "label": "Show the hostname used",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",instance=~\"$instance\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Overview (associated JOB items) currently selected host：【$show_hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Resources Overview : 【JOB：$job】",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"$job\"} * on(instance) group_right(product) windows_cs_hostname"
    },
    {
     "expr": "time() - windows_system_system_up_time{job=~\"$job\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "windows_cs_logical_processors{job=~\"$job\"} - 0",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU usage%"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\"} - 0",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "Memory Usage%"
    },
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=~\"$job\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\",volume=~\"C:\"})",
     "legendFormat": "C:/ Drive Usage"
    },
    {
     "expr": "max by (instance) (1 - windows_logical_disk_free_bytes{job=~\"$job\", volume=~\".:\"}/windows_logical_disk_size_bytes{job=~\"$job\", volume=~\".:\"})",
     "legendFormat": "Partition Used%"
    },
    {
     "expr": "windows_os_processes{job=~\"$job\"}",
     "legendFormat": "Number of processes"
    },
    {
     "expr": "sum by (instance) (windows_service_state{job=~\"$job\",state=~\"running\"})",
     "legendFormat": "Running Services"
    },
    {
     "expr": "max(rate(windows_net_bytes_sent_total{job=~\"$job\", nic!~\"(?i:(.*(isatap|VPN).*))\"}[2m]) * 8) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(rate(windows_net_bytes_sent_total{job=~\"$job\", nic!~\"(?i:(.*(isatap|VPN).*))\"}[2m]) * 8) by (instance)",
     "legendFormat": "Upload"
    },
    {
     "expr": "max(rate(windows_logical_disk_read_bytes_total{job=~\"$job\", volume=~\".:\"}[2m])) by (instance)",
     "legendFormat": "Disk Read"
    },
    {
     "expr": "max(rate(windows_logical_disk_write_bytes_total{job=~\"$job\", volume=~\".:\"}[2m])) by (instance)",
     "legendFormat": "Disk Write"
    }
   ]
  },
  {
   "title": "CPU usage by host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage by host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100.0 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Maximum traffic NIC network details by host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_net_bytes_sent_total{job=~\"$job\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_net_bytes_received_total{job=~\"$job\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Maximum disk read/write details by host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_logical_disk_read_bytes_total{job=~\"$job\", volume=~\".:\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Read",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_logical_disk_write_bytes_total{job=~\"$job\", volume=~\".:\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Write",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Maximum disk IO details by host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_logical_disk_reads_total{job=~\"$job\", volume=~\".:\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Read",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_logical_disk_writes_total{job=~\"$job\", volume=~\".:\"}[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Write",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Resource Details 【$show_hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 27 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - windows_system_system_up_time{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[2m])))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage rate by partition",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{job=~\"$job\", instance=~\"$instance\", volume=~\".:\"} / windows_logical_disk_size_bytes{job=~\"$job\", instance=~\"$instance\", volume=~\".:\"}) * 100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{job=~\"$job\",instance=~\"$instance\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_processes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Number of processes"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 29 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 31 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[5m]))*100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Physical Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Physical Memory Remaining",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_virtual_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Virtual Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "windows_os_virtual_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Free Virtual Memory"
    }
   ]
  },
  {
   "title": "Disk space remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Space remaining {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Space {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_sent_total{job=~\"$job\",instance=~\"$instance\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) * 8 > 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Sent-Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_bytes_received_total{job=~\"$job\",instance=~\"$instance\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) * 8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Received-Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_reads_total{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_writes_total{job=~\"$job\",instance=~\"$instance\", volume=~\".:\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round((irate(windows_net_bytes_total{job=~\"$job\",instance=~\"$instance\",nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) * 8 / (windows_net_current_bandwidth_bytes{job=~\"$job\",instance=~\"$instance\",nic!~\"(?i:(.*(isatap|VPN).*))\"} * 8)) * 100)",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_outbound_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) + irate(windows_net_packets_outbound_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}_outbound",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_net_packets_received_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~\"(?i:(.*(isatap|VPN).*))\"}[5m]) + irate(windows_net_packets_received_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}_received",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{job=~\"$job\",instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "System Threads",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System Exception Dispatches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_system_exception_dispatches_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Exceptions",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}